# %% [markdown]
# # Climate Change Modeling Interactive Analysis
# 
# This notebook allows you to interactively explore the climate data and model predictions.

# %%
import sys
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Add the src directory to the path so we can import modules
sys.path.append(os.path.abspath(os.path.join('..', 'src')))

from data_loader import load_data, preprocess_data
from models import ClimateModel

# %% [markdown]
# ## 1. Load Data
# We load the data generated by the main script.

# %%
data_path = os.path.join('..', 'data', 'climate_data.csv')
if not os.path.exists(data_path):
    print("Data not found! Please run src/main.py first or generate it here.")
    # from data_generator import generate_synthetic_data
    # generate_synthetic_data(data_path)
else:
    df = load_data(data_path)
    print("Data loaded successfully.")
    print(df.head())

# %% [markdown]
# ## 2. Data Exploration
# Let's look at the correlation between CO2 and Temperature.

# %%
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='CO2_Concentration', y='Global_Temp_Anomaly', hue='Year')
plt.title('CO2 vs Temperature Anomaly')
plt.grid(True)
plt.show()

# %% [markdown]
# ## 3. Model Training & Prediction
# We can retrain the model and inspect feature importances.

# %%
X_train, X_test, y_train, y_test, scaler, feature_names = preprocess_data(df)
model = ClimateModel('random_forest')
model.train(X_train, y_train)
results = model.evaluate(X_test, y_test)

print("R2 Score:", results['R2'])

# %% [markdown]
# ## 4. Future Projections (What-If Analysis)
# What if CO2 doubles? (Mock scenario)

# %%
# Access the underlying model
rf = model.model
importances = rf.feature_importances_
indices = pd.Series(importances, index=feature_names).sort_values(ascending=False)

plt.figure(figsize=(10,6))
indices.plot(kind='bar')
plt.title('Feature Importance')
plt.show()

# %%
